server:
  port: ${CUSTOM.SERVER.PORT:9080}

# Spring Cloud Gateway Router
spring:
  cloud:
    gateway:
      routes:

        - id: document-service-route
          uri: lb://document-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/document-service/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=paramName, paramValue

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2

        - id: customer-service-route
          uri: lb://customer-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/customer-service/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=paramName, paramValue

        - id: category-service-route
          uri: lb://category-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/category-service/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=paramName, paramValue

        - id: license-service-route
          uri: lb://license-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/license-service/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=paramName, paramValue