server:
  port: ${CUSTOM.SERVER.PORT:9080}

# Spring Cloud Gateway Router
spring:
  cloud:
    gateway:
      routes:

        - id: document-service-route
          uri: lb://document-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/document-service/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=paramName, paramValue

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true