version: '3.9'

services:

  mongo-service:
    image: mongo
    container_name: agutierrezl-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: agutierrezl
      MONGO_INITDB_ROOT_PASSWORD: agutierrezl
    ports:
      - 27017:27017
    networks:
      - agutierrezl

  mongo-express:
    image: mongo-express
    container_name: agutierrezl-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: agutierrezl
      ME_CONFIG_MONGODB_ADMINPASSWORD: agutierrezl
      ME_CONFIG_MONGODB_URL: mongodb://agutierrezl:agutierrezl@mongo-service:27017
    networks:
      - agutierrezl

networks:
  agutierrezl:
    name: agutierrezl-network
  